version: '3'
services:
        bot:
                build: .
                ports:
                        - 8080:8080
                environment: 
                        - PORT=808
                        - NUM_THREADS=1
                        - POLLING=1
                        - TOKEN=${TOKEN}
                        - HOST=${HOST}
                        - ADMINS=${ADMINS}
                        - FIREBASE_URL=${FIREBASE_URL}

